site_name: MAVIS

theme:
  name: material
repo_url: https://github.com/bcgsc/mavis
repo_name: github
site_dir: build-docs
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - markdown_include.include:
      base_path: docs
extra_css: [extra.css]
nav:
  - index.md
  - install.md
  - migrating.md
  - ... | background/**.md
  - ... | inputs/**.md
  - ... | outputs/**.md
  - ... | configuration/**.md
  - ... | tutorials/**.md
  - development.md
  - ...
  - glossary.md

plugins:
  - search
  - awesome-pages
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:build_package_docs"
